homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 289
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Los_Angeles
  # Customization file
  customize: !include customize.yaml

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
logger:
zwave:
  device_config:
    light.office_front_lights_switch_level:
      refresh_value: true
      delay: 2
recorder:
  db_url: !secret db_mysql

####   Custom Updater for addons  ####
# from here:  https://github.com/custom-components/custom_updater/wiki/Installation   #
# this is linked to ~/git-repos  
####  
custom_updater:
  
#### MyQ setup for Garage doors ####     
cover:
  - platform: myq
    username: !secret myq_user
    password: !secret myq_password
    type: chamberlain

    
# Show the introduction message on startup. 
introduction:

#### Setup external access ####
http:
    base_url: !secret base_url
    use_x_forwarded_for: true
    trusted_proxies: 127.0.0.1

# Discover some devices automatically
discovery:

#### Setup Influxdb access to send all stats ####
influxdb:
  host: !secret influxdb_host


# Sensors
sensor:
  # Weather prediction
  - platform: darksky
    api_key: !secret darksky_api_key
    forecast:
      - 3
    monitored_conditions:
      - summary
      - icon
      - temperature

      
#Fix Binary Sensors      
binary_sensor:
  - platform: template
    sensors:
      ##### Makes Fibaro Sensor act like Binary sensor
      garage_basement_door_vsensor:
        device_class: opening
        friendly_name: "Garage Basement Door"
        value_template: "{{ is_state('sensor.garage_basement_door_sensor_access_control', '22') }}"
      ##### Makes AEON Labs ZW089 Recessed Door sensor show as door
      office_slider_door_vsensor:
        device_class: opening
        friendly_name: "Office Slider Door"
        value_template: "{{ is_state('binary_sensor.office_slider_sensor', 'on') }}"
      ##### Makes AEON Labs ZW089 Recessed Door sensor show as door
      server_room_door_vsensor:
        device_class: opening
        friendly_name: "Server Room Door"
        value_template: "{{ is_state('binary_sensor.server_room_door_sensor', 'on') }}"
      
# Text to speech
tts:
  - platform: google

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

#tesla:
#  username: !secret tesla_username
#  password: @secret tesla_password
ecobee:
  api_key: !secret ecobee_api_key
cloud:
  google_actions:
    filter:
      include_domains:
        - light
        - climate
##### Fine IOS Devices
ios:
